name: CI

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  UseMultiToolTask: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
        platform: [Win32]

    steps:
    - name: Add Windows 11 SDK + WDK components
      run: "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify ^
      --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" ^
      --add Microsoft.VisualStudio.Component.Windows10SDK.26100 ^
      --add Microsoft.VisualStudio.Component.Windows11SDK.26100 ^
      --add Microsoft.VisualStudio.Component.WindowsDriverKit ^
      --quiet --wait --norestart --nocache
    - name: Verify d3dumddi.h
      run: dir "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\d3dumddi.h"
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: microsoft/setup-msbuild@v1
    - uses: Trass3r/setup-cpp@master
    - name: Build
      run: msbuild /m /p:Configuration=${{ matrix.config }} /p:Platform=${{ matrix.platform }} dxwrapper.sln
    - name: Upload DX7 Artifacts
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: dx7 game binaries
        path: bin/${{ matrix.config }}/dx7/*
    - name: Upload DX8 Artifacts
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: dx8 game binaries
        path: bin/${{ matrix.config }}/dx8/*
    - name: Upload DX9 Artifacts
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: dx9 game binaries
        path: bin/${{ matrix.config }}/dx9/*
    - name: Upload Matrix Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config }} binaries
        path: bin/${{ matrix.config }}/*
